# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='initialized', max_length=30)),
                ('result', models.TextField(default='None', max_length=700)),
                ('default_method', models.CharField(default='odds_ratio', max_length=30)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.CharField(default='Jessica', max_length=30)),
                ('first_name', models.CharField(default='Christopher', max_length=30)),
                ('middle_name', models.CharField(default='Cassie', max_length=30)),
                ('last_name', models.CharField(default='Smith', max_length=30)),
                ('nick_name', models.CharField(default='', max_length=30)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('birth_country', models.CharField(default='Barbados', max_length=30)),
                ('birth_state', models.CharField(default='Delaware', max_length=30)),
                ('birth_city', models.CharField(default='South Amy', max_length=30)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('death_country', models.CharField(default='Uzbekistan', max_length=30)),
                ('death_state', models.CharField(default='Nebraska', max_length=30)),
                ('death_city', models.CharField(default='West Taraberg', max_length=30)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('final_game', models.DateTimeField(blank=True, null=True)),
                ('retro_id', models.CharField(default='Joseph', max_length=30)),
                ('bbref_id', models.CharField(default='Mary', max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('bats', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='', max_length=30)),
                ('throws', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='', max_length=30)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('league', models.CharField(default='', max_length=30)),
                ('category', models.CharField(choices=[(0, 'Teams'), (1, 'AwardsManagers'), (2, 'SeriesPost'), (3, 'TeamsHalf'), (4, 'Salaries'), (5, 'Managers'), (6, 'HomeGames'), (7, 'AllstarFull'), (8, 'AwardsSharePlayers'), (9, 'FieldingOF'), (10, 'Fielding'), (11, 'CollegePlaying'), (12, 'ManagersHalf'), (13, 'PitchingPost'), (14, 'Appearances'), (15, 'Schools'), (16, 'Pitching'), (17, 'HallOfFame'), (18, 'Batting'), (19, 'AwardsPlayers'), (20, 'BattingPost'), (21, 'FieldingPost'), (22, 'Master'), (23, 'AwardsShareManagers'), (24, 'Parks'), (25, 'TeamsFranchises')], default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('abbr', models.CharField(default='', max_length=30)),
                ('value_str', models.CharField(default='', max_length=30)),
                ('value', models.DecimalField(decimal_places=7, default=0, max_digits=19)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='baseball.Player')),
            ],
            options={
                'ordering': ['name', 'player'],
            },
        ),
        migrations.AddField(
            model_name='pitch',
            name='batter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='baseball.Player'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitcher', to='baseball.Player'),
        ),
    ]
